audio_decoder: none none
video_decoder: maxWidth 0 maxHeight 0
svp_allocator: none 1
 
# Policy configuration section
policy: requester-wins-priority-tie
policy: revoke-timeout(6000)
policy: unauthorized-requests-abort
policy default-client-priority (0)          # Default priority for new clients

