#!/bin/sh
# kbd ptest run-ptest
# Based on upstream OE-Core implementation by Qiu Tingting

# Define test work dir
WORKDIR=/usr/lib/kbd/ptest/tests/

# Run test
cd ${WORKDIR}

# create atconfig
if [[ ! -f "atconfig" ]]; then
    echo 'abs_builddir="/usr/lib/kbd/ptest/tests/"' > atconfig
    echo 'abs_srcdir="/usr/lib/kbd/ptest/tests/"' >> atconfig
    echo 'abs_top_builddir="/usr/lib/kbd/ptest/"' >> atconfig
fi

./testsuite -k unittest | sed -e '/[0-9]:/s/://' \
    -e '/ ok/s/^/PASS: /;/ FAILED/s/^/FAIL: /;/ skipped/s/^/SKIP: /' \
    -e '/ ok/s/ ok.*//;/ skipped/s/ skipped.*//;/ FAILED/s/ FAILED.*//'
