#!/bin/bash
# kbd ptest run-ptest
# Based on upstream OE-Core implementation by Qiu Tingting

# Define test work dir
WORKDIR=@PTEST_PATH@/tests/

# Run test
cd ${WORKDIR}

# create atconfig
if [ ! -f "atconfig" ]; then
    echo "abs_builddir=\"@PTEST_PATH@/tests/\"" > atconfig
    echo "abs_srcdir=\"@PTEST_PATH@/tests/\"" >> atconfig
    echo "abs_top_builddir=\"@PTEST_PATH@/\"" >> atconfig
fi

./testsuite -k unittest | sed -e '/[0-9]:/s/://' \
    -e '/ ok/s/^/PASS: /;/ FAILED/s/^/FAIL: /;/ skipped/s/^/SKIP: /' \
    -e '/ ok/s/ ok.*//;/ skipped/s/ skipped.*//;/ FAILED/s/ FAILED.*//'
