PACKAGECONFIG_remove_kirkstone = "gnutls"
PACKAGECONFIG_class-native_remove_kirkstone = "gnutls"
PACKAGECONFIG_append_kirkstone = " openssl"
PACKAGECONFIG_class-native_append_kirkstone = " openssl"
PACKAGECONFIG_remove += "libproxy"
