#!/bin/sh

cd test
for i in `grep -vE "@|^$|#|Gt-dummy" Maketests | awk -F: '{print $1}'`; do
    LC_ALL=${GAWKLOCALE:-C} LANG=${GAWKLOCALE:-C} srcdir=`pwd` AWK=gawk CMP=cmp \
        make -f Maketests $i >$i.tmp 2>&1
    make_status=$?
    
    if [ $make_status -ne 0 ] || grep -q "Error" $i.tmp; then
        echo "FAIL: $i"
    else
        echo "PASS: $i"
        rm -f $i.tmp
    fi
done
