name: OSS Release Dry Run

on:
  workflow_dispatch:
    inputs:
      last_release_tag:
        description: "Previous Release Tag"
        required: true
        default: "4.13.0"

      next_release_tag:
        description: "Next Release Tag"
        required: true
        default: "4.14.0"

      release_type:
        description: "Release Type"
        required: true
        default: "major"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release-dry-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Execute Release Dry Run
        env:
          RDK_E_GITHUB_TOKEN: ${{ secrets.RDK_E_GITHUB_TOKEN }}
          RDKCENTRAL_GITHUB_TOKEN: ${{ secrets.RDKCENTRAL_GITHUB_TOKEN }}
        run: |
          python3 release_dry_run.py \
            --mode run \
            --manifest-repo rdk-e/rdke-oss-manifest \
            --last-release-tag "${{ inputs.last_release_tag }}" \
            --next-release-tag "${{ inputs.next_release_tag }}" \
            --release-type "${{ inputs.release_type }}" \
            --rdk-e-token "$RDK_E_GITHUB_TOKEN" \
            --rdkcentral-token "$RDKCENTRAL_GITHUB_TOKEN"
